name: Build Full App

on:
  workflow_dispatch:

jobs:
  frontend:
    name: Build Frontend
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: |
            cd Ui
            dotnet restore

      - name: Publish
        run: |
            cd Ui
            dotnet publish -c Release

      - name: Upload .NET Build
        uses: actions/upload-artifact@v4
        with:
          name: net-build
          path: Ui/bin/Release/net10.0/win-x64/publish/Vice.Ui.exe

  updater:
    name: Build updater
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build Updater
        shell: pwsh
        run: |
          cd updater
          cargo build -r

      - name: Upload Updater
        uses: actions/upload-artifact@v4
        with:
          name: updater
          path: updater/target/release/updater.exe

  app:
    name: Build Rust App
    runs-on: windows-latest
    needs: [frontend, updater]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Download .NET Build
        uses: actions/download-artifact@v4
        with:
          name: net-build
          path: Ui/bin/Release/net10.0/win-x64/publish

      - name: Install C++ Compiler
        shell: pwsh
        run: |
          choco install mingw -y
          refreshenv

      - name: Download Updater
        uses: actions/download-artifact@v4
        with:
          name: updater
          path: updater/target/release

      - name: Build Rust App
        shell: bash
        run: |
          cargo build --release

      - name: Package Release Zip
        shell: pwsh
        run: |
          Compress-Archive -Path target/release/Vice.exe, LICENSE, docs/Installation.md -DestinationPath windows.zip -Force

      - name: Upload Final Zip
        uses: actions/upload-artifact@v4
        with:
          name: full-windows
          path: windows.zip